image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_CURRENT_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-$CI_BUILD_REF
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-latest

manual_build:
  stage: build
  except:
    - recette
    - production
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_IMAGE .
    - docker push $CONTAINER_CURRENT_IMAGE
  when: manual

recette_build:
  stage: build
  only:
    - recette
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_IMAGE .
    - docker push $CONTAINER_CURRENT_IMAGE

production_build:
  stage: build
  only:
    - production
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_IMAGE .
    - docker push $CONTAINER_CURRENT_IMAGE

release:
  stage: release
  only:
    - recette
    - production
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_CURRENT_IMAGE
    - docker tag $CONTAINER_CURRENT_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE

deploy_recette:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment:
    name: recette
    url: https://cv.sraleik.fr
  only:
    - recette
  script:
    - upgrade --environment production --stack sraleik-cv-recette --service apache --new-image registry.gitlab.com/sraleik/sraleik_cv:recette-latest --no-finish-upgrade
