image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CURRENT_COMMIT_SLUG: ${CI_BUILD_REF:0:6}
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME_$CI_BUILD_REF_NAME:$CURRENT_COMMIT_SLUG
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME_$CI_BUILD_REF_NAME:latest

before_script:
  - docker -v
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_PROJECT_NAME
  - echo $CI_BUILD_REF_NAME
  - echo ${CI_BUILD_REF:0:6}
  - echo $CURRENT_COMMIT_SLUG
  - echo $CONTAINER_TEST_IMAGE
  - echo $CONTAINER_LATEST_IMAGE

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  when: manual

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE /test/docker_test.sh
  when: manual

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push registry.gitlab.com/sraleik/sraleik_cv_$CI_BUILD_REF_NAME:latest
  when: manual
